language: ruby
rvm:
- 2.2
- 2.1
- 2.0.0
env:
- secure: Uqiq8YPDkJZZUWx7bS/Gta/AkdIP1J3S/i96zDWfQaZRJhzDbE/KgtDCIrSn+q6cohuYzk4HbyT2Dh+4gf+xUpcJF+P9Eg/HeEiw7xjk2JopzBpbJc1uK7abrZW523yDhRZv//Ad0rZjuD0hJqveM3RwPWX1TFbh3RLafIjoXRY=
notifications:
  slack:
    secure: URMb+Pjhj05U45pemqlC/EhepRTl0OK3VW2sCydXtSdf4DWrD7hso+zj/7k0KrmvqOEiv3/GK2f05cxf8NnHIMb3t1sM5+h4ACTdIKNtHYsVCXqXGfziOmNM3lY/0lGS36QJnR7M3fHc+YJYxcuB1gAr+Fqh2Ifzd3UuOZEbwu4=
